# Generated by Django 4.0.3 on 2022-04-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('review', models.TextField(max_length=1024)),
            ],
        ),
    ]
