# Generated by Django 4.0.3 on 2022-04-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaapp', '0003_contact_number_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.SmallIntegerField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
