# Generated by Django 4.0.3 on 2022-04-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaapp', '0008_alter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
