# Generated by Django 4.0.3 on 2022-04-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romaapp', '0009_alter_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
    ]
