# Generated by Django 4.0.3 on 2022-04-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romaapp', '0010_remove_contact_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
