# Generated by Django 4.0.3 on 2022-04-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaapp', '0011_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='grettings_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='grettings_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_name',
            field=models.CharField(max_length=20),
        ),
    ]
