# Generated by Django 4.0.3 on 2022-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaapp', '0012_alter_about_career_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=100),
        ),
    ]
