# Generated by Django 4.0.3 on 2022-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaapp', '0013_alter_skills_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
