# Generated by Django 4.0.3 on 2022-04-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaapp', '0015_remove_portfolio_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('review', models.TextField(max_length=1024)),
            ],
        ),
    ]
