# Generated by Django 4.0.3 on 2022-04-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaapp', '0016_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='review',
            field=models.TextField(max_length=2048),
        ),
    ]
